/**
* jQuery Nivo Slider v2.7.1
* http://nivo.dev7studios.com
*
* Copyright 2011, Gilbert Pellegrom
* Free to use and abuse under the MIT license.
* http://www.opensource.org/licenses/mit-license.php
*
* January 2012
*/
(function(g){var C=function(A,t){var a=g.extend({},g.fn.nivoSlider.defaults,t),a={effect:a.effect,slices:a.slices,boxCols:a.boxCols,boxRows:a.boxRows,animSpeed:a.animSpeed,pauseTime:a.pauseTime,startSlide:a.startSlide,directionNav:a.directionNav,directionNavHide:a.directionNavHide,controlNav:a.controlNav,controlNavThumbs:a.controlNavThumbs,controlNavThumbsFromRel:a.controlNavThumbsFromRel,controlNavThumbsSearch:a.controlNavThumbsSearch,controlNavThumbsReplace:a.controlNavThumbsReplace,keyboardNav:a.keyboardNav,
pauseOnHover:a.pauseOnHover,manualAdvance:a.manualAdvance,captionOpacity:a.captionOpacity,prevText:a.prevText,nextText:a.nextText,randomStart:a.randomStart,beforeChange:a.beforeChange,afterChange:a.afterChange,slideshowEnd:a.slideshowEnd,lastSlide:a.lastSlide,afterLoad:a.afterLoad},e={previousSlideIndex:0,currentSlideIndex:0,currentImage:{},totalSlides:0,running:!1,paused:!1,stop:!1},c,s,u,o,v,z,w,k,B;c=g(A);c.data("nivo:vars",e);c.css("position","relative");c.addClass("nivoSlider");s=c.children();
u=c.children("a")||!1;for(var q=s.length,n=0,x=0;--q+1;)k=g(s[q]),k.is("img")||(k=k.find("img").eq(0)),n=k.width(),x=k.height(),0===n&&(n=k.attr("width")),0===x&&(x=k.attr("height")),n>c.width()&&c.width(n),x>c.height()&&c.height(x),k.css("display","none"),++e.totalSlides;u&&u.addClass("nivo-imageLink");a.randomStart&&(a.startSlide=Math.floor(Math.random()*e.totalSlides));0<a.startSlide&&(a.startSlide>=e.totalSlides&&(a.startSlide=e.totalSlides-1),e.previousSlideIndex=a.startSlide-1,e.currentSlideIndex=
a.startSlide);o=g(s[e.currentSlideIndex]);e.currentImage=o.is("img")?o:o.find("img").eq(0);e.currentImage={url:e.currentImage.attr("src"),title:e.currentImage.attr("title")};o.is("a")&&o.css("display","block");c.css("background",'url("'+e.currentImage.url+'") no-repeat').append(g('<div class="nivo-caption"><p></p></div>').css({display:"none",opacity:a.captionOpacity}));v=g(".nivo-caption",c);z=v.find("p");v.css("opacity",0);var D=function(){var b=e.currentImage.title||null;if(b){b.substr(0,1)=="#"&&
(b=g(b).html());v.css("opacity")!=0?z.stop().fadeTo(a.animSpeed,0,function(){z.html(b).stop().fadeTo(a.animSpeed,1)}):z.html(b)}v.stop().fadeTo(a.animSpeed,b?a.captionOpacity:0)};D();if(2>e.totalSlides)return!1;var l=null;a.manualAdvance||(l=setInterval(function(){p(false)},a.pauseTime));a.directionNav&&(c.append('<div class="nivo-directionNav"><a class="nivo-prevNav" data-dir="prev">'+a.prevText+'</a><a class="nivo-nextNav" data-dir="next">'+a.nextText+"</a></div>"),w=g(".nivo-directionNav",c),a.directionNavHide&&
(w.hide(),c.hover(function(){w.show()},function(){w.hide()})),w.children().click(function(){var a=g(this).data("dir")||"next";if(e.running)return false;clearInterval(l);l=null;if(a==="prev")e.currentSlideIndex=e.currentSlideIndex-2;p(a)}));if(a.controlNav){k=q="";for(n=s.length;--n+1;)a.controlNavThumbs?(k=g(s[n]),k.is("img")||(k=k.find("img").eq(0)),k=a.controlNavThumbsFromRel?'<img src="'+k.attr("rel")+'" alt="" />':'<img src="'+k.attr("src").replace(a.controlNavThumbsSearch,a.controlNavThumbsReplace)+
'" alt="" />'):k=n+1,q='<a class="nivo-control" data-slide="'+n+'">'+k+"</a>"+q;c.append('<div class="nivo-controlNav">'+q+"</div>");k=g(".nivo-controlNav",c);B=k.find("a");B.click(function(){var a=g(this);if(e.running||a.hasClass("active"))return false;clearInterval(l);l=null;c.css("background",'url("'+e.currentImage.url+'") no-repeat');e.currentSlideIndex=a.data("slide")-1;p("control")}).eq(e.currentSlideIndex).addClass("active")}a.keyboardNav&&g(document).keydown(function(a){a=a.keyCode||a.which;
if(e.running)return false;clearInterval(l);l=null;if(a===37||a===63234){e.currentSlideIndex=e.currentSlideIndex-2;p("prev")}else(a===39||a===63235)&&p("next")});a.pauseOnHover&&c.hover(function(){e.paused=true;clearInterval(l);l=null},function(){e.paused=false;l===null&&!a.manualAdvance&&(l=setInterval(function(){p(false)},a.pauseTime))});c.bind("nivo:animFinished",function(){e.running=false;o.is("a")&&o.css("display","block");l===null&&!e.paused&&!a.manualAdvance&&(l=setInterval(function(){p(false)},
a.pauseTime));a.afterChange.call(this)});var r=function(b){var f=c.width(),d=0,b=b||a.slices,y=document.createDocumentFragment(),j,i,h={background:"",left:"",width:"",height:"0",opacity:0};do{j=Math.round(f/b);i=j*d;h.left=i+"px";h.background='url("'+e.currentImage.url+'") no-repeat -'+(j+i-j)+"px 0%";h.width=j+"px";if(d===b-1)h.width=f-i+"px";y.appendChild(g('<div class="nivo-slice"></div>').css(h)[0])}while(++d<b);c.append(y)},E=function(){var b=c.width(),f=Math.round(b/a.boxCols),d=Math.round(c.height()/
a.boxRows),y=document.createDocumentFragment(),j=0,i=0,h=0,m={background:'url("'+e.currentImage.url+'") no-repeat',backgroundPosition:"",left:"",top:"",width:"",height:d+"px",opacity:0};do{m.top=d*i+"px";m.width=f+"px";do{j=f*h;m.left=j+"px";m.backgroundPosition="-"+(f+j-f)+"px -"+(d+i*d-d)+"px";if(h===a.boxCols-1)m.width=b-j+"px";y.appendChild(g('<div class="nivo-box"></div>').css(m)[0])}while(++h<a.boxCols);h=0}while(++i<a.boxRows);c.append(y)},p=function(b){var f=c.data("nivo:vars");f&&f.currentSlideIndex==
f.totalSlides-1&&a.lastSlide.call(this);if((!f||f.stop)&&!b)return false;a.beforeChange.call(this);c.css("background",'url("'+f.currentImage.url+'") no-repeat');++f.currentSlideIndex;if(f.currentSlideIndex>=f.totalSlides){f.currentSlideIndex=0;a.slideshowEnd.call(this)}else if(f.currentSlideIndex<0)f.currentSlideIndex=f.totalSlides-1;o=g(s[f.currentSlideIndex]);f.previousImage=f.currentImage;f.currentImage=o.is("img")?o:o.find("img").eq(0);f.currentImage={url:f.currentImage.attr("src"),title:f.currentImage.attr("title"),
transition:f.currentImage.data("transition")};a.controlNav&&B.removeClass("active").eq(f.currentSlideIndex).addClass("active");u&&u.css("display","none");D();g(".nivo-slice",c).remove();g(".nivo-box",c).remove();var d=a.effect||"fade";if(a.effect==="random"){d=["sliceDownRight","sliceDownLeft","sliceUpRight","sliceUpLeft","sliceUpDown","sliceUpDownLeft","fold","fade","cycle","boxRandom","boxRain","boxRainReverse","boxRainGrow","boxRainGrowReverse"];d=d[Math.floor(Math.random()*(d.length-1))]}else if(a.effect.indexOf(",")!==
-1){d=a.effect.split(",");d=d[Math.floor(Math.random()*d.length)]}if(f.currentImage.transition)d=f.currentImage.transition;f.running=true;var e=function(b,d,f,e,g){setTimeout(function(){b.animate(d,f||a.animSpeed,"",g&&function(){c.trigger("nivo:animFinished")})},100+e)};switch(d){case "sliceDown":case "sliceDownRight":case "sliceDownLeft":r();var b=0,j=g(".nivo-slice",c),i=0,h;d==="sliceDownLeft"&&(j=j._reverse());do{h=g(j[i]);h.css({top:"0"});e(h,{height:"100%",opacity:1},null,b,i===a.slices-1?
true:false);b=b+50}while(++i<a.slices);break;case "sliceUp":case "sliceUpRight":case "sliceUpLeft":r();b=0;j=g(".nivo-slice",c);i=0;d==="sliceUpLeft"&&(j=j._reverse());do{h=g(j[i]);h.css({bottom:"0"});e(h,{height:"100%",opacity:1},null,b,i===a.slices-1?true:false);b=b+50}while(++i<a.slices);break;case "sliceUpDown":case "sliceUpDownRight":case "sliceUpDownLeft":r();var m=b=0,j=g(".nivo-slice",c),i=0;d==="sliceUpDownLeft"&&(j=j._reverse());do{h=g(j[i]);m?h.css("top","0"):h.css("bottom","0");m=!m;e(h,
{height:"100%",opacity:1},null,b,i===a.slices-1?true:false);b=b+50}while(++i<a.slices);break;case "fold":r();b=0;j=g(".nivo-slice",c);d=i=0;do{h=g(j[i]);d=h.width();h.css({top:"0",height:"100%",width:"0"});e(h,{width:d+"px",opacity:1},null,b,i===a.slices-1?true:false);b=b+50}while(++i<a.slices);break;default:case "fade":r(1);h=g(".nivo-slice",c);h.css({width:c.width()+"px",height:"100%"}).animate({opacity:1},a.animSpeed*2,"",function(){c.trigger("nivo:animFinished")});break;case "cycle":case "cycleLeft":case "cycleRight":r(1);
e=c.width();h=g(".nivo-slice",c);d=d==="cycleLeft"||d==="cycle"&&(b==="prev"||b==="control"&&f.currentSlideIndex<f.previousSlideIndex)?true:false;i=document.createDocumentFragment();b={position:"absolute",right:d?"0":e+"px",background:'url("'+f.previousImage.url+'")',width:e+"px",height:"100%"};j={position:"absolute",right:d?e+"px":"0",background:'url("'+f.currentImage.url+'")',width:e+"px",height:"100%"};i.appendChild(g("<div></div>").css(b)[0]);i.appendChild(g("<div></div>").css(j)[0]);h.html(i);
b={left:d?-e+"px":"0",width:e*2+"px",height:"100%",opacity:1};h.css(b).animate({left:d?"0":-e+"px"},a.animSpeed*2,"",function(){c.trigger("nivo:animFinished")});break;case "slideInHorizontal":case "slideInLeft":case "slideInRight":r(1);h=g(".nivo-slice",c);d=d==="slideInLeft"||d==="slideInHorizontal"&&(b==="prev"||b==="control"&&f.currentSlideIndex<f.previousSlideIndex)?true:false;b={left:d?"0":"",right:d?"":"0",backgroundPosition:d?"100% 0":"0 0",width:"0",height:"100%",opacity:1};h.css(b).animate({width:"100%"},
a.animSpeed*2,"",function(){c.trigger("nivo:animFinished")});break;case "slideInVertical":case "slideInTop":case "slideInBottom":r(1);h=g(".nivo-slice",c);d=d==="slideInTop"||d==="slideInVertical"&&(b==="prev"||b==="control"&&f.currentSlideIndex>f.previousSlideIndex)?true:false;b={top:d?"0":"",bottom:d?"":"0",backgroundPosition:d?"0 100%":"0 0",width:"100%",height:"0",opacity:1};h.css(b).animate({height:"100%"},a.animSpeed*2,"",function(){c.trigger("nivo:animFinished")});break;case "boxRandom":E();
h=a.boxCols*a.boxRows;var b=0,k=C(g(".nivo-box",c)),l=0;do{m=g(k[l]);e(m,{opacity:1},null,b,l===h-1?true:false);b=b+20}while(++l<h);break;case "boxRain":case "boxRainReverse":case "boxRainGrow":case "boxRainGrowReverse":E();h=a.boxCols*a.boxRows;var b=0,j=[],n=m=0,k=g(".nivo-box",c),l=0,i=h;if(d=="boxRainReverse"||d=="boxRainGrowReverse")k=k._reverse();j[m]=[];do{j[m][n]=k[l];++n;++l;if(n===a.boxCols){++m;j[m]=[];n=0}}while(--i);var p=i=n=l=k=0,q=0;do{n=k;do{if(n>=0&&n<a.boxCols){m=g(j[l][n]);p=m.width();
q=m.height();(d=="boxRainGrow"||d=="boxRainGrowReverse")&&m.width(0).height(0);e(m,{width:p,height:q,opacity:1},a.animSpeed/1.3,b,++i===h?true:false)}--n}while(++l<a.boxRows);l=0;b=b+100}while(++k<a.boxCols*2)}f.previousSlideIndex=f.currentSlideIndex},C=function(a){for(var c,d,e=a.length;e;c=parseInt(Math.random()*e),d=a[--e],a[e]=a[c],a[c]=d);return a};this.stop=function(){if(!c.data("nivo:vars").stop)c.data("nivo:vars").stop=true};this.start=function(){if(c.data("nivo:vars").stop)c.data("nivo:vars").stop=
false};a.afterLoad.call(this);return this};g.fn.nivoSlider=function(A){return this.each(function(){var t=g(this);if(t.data("nivoslider"))return t.data("nivoslider");var a=new C(this,A);t.data("nivoslider",a)})};g.fn.nivoSlider.defaults={effect:"random",slices:15,boxCols:8,boxRows:4,animSpeed:500,pauseTime:3E3,startSlide:0,directionNav:!0,directionNavHide:!0,controlNav:!0,controlNavThumbs:!1,controlNavThumbsFromRel:!1,controlNavThumbsSearch:".jpg",controlNavThumbsReplace:"_thumb.jpg",keyboardNav:!0,
pauseOnHover:!0,manualAdvance:!1,captionOpacity:0.8,prevText:"Prev",nextText:"Next",randomStart:!1,beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};g.fn._reverse=[].reverse})(jQuery);